name: "nightly build-jdk nightly"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  hotspot14:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016]
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          echo "::set-output name=branch::$(echo ${GITHUB_HEAD_REF})"
          echo "::set-output name=repo::$(echo ${{ github.event.pull_request.head.repo.full_name }})"
        else
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=repo::$(echo ${{ github.repository }})"
        fi
      id: extract_branch
    - name: testing github.repository
      run: echo ${{ github.repository }}
    - name: Testing
      run: |
        echo " full name is ${{ github.event.pull_request.head.repo.full_name }} ref is ${GITHUB_HEAD_REF}"
        echo " repo is ${{ steps.extract_branch.outputs.repo }} branch is ${{ steps.extract_branch.outputs.branch }}"